# Generated by Django 4.0.5 on 2022-07-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_rename_text_form_name_alter_question_text_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
    ]
