# Generated by Django 4.0.5 on 2022-07-07 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_rename_answers_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 14, 20, 34, 227813, tzinfo=utc), verbose_name='date published'),
        ),
    ]
