# Generated by Django 4.0.5 on 2022-07-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_form_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='form',
        ),
        migrations.AddField(
            model_name='form',
            name='questions',
            field=models.ManyToManyField(to='forms.question'),
        ),
        migrations.AlterField(
            model_name='form',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
